gen city = substr(watitle,1,ustrpos(watitle,",")-1)
replace city = strtrim(city)
gen state = substr(watitle,ustrpos(watitle,",")+1,.)
replace state = strtrim(state) //get rid of leading/trailing blanks

replace state = "ARKANSAS" if state == "ARKANAS"
replace state = "FLORIDA" if state == "FLORDIA"
replace state = "BERMUDA" if state=="BURMUDA"
replace city = "ATLANTA" if state == "ATLANTA -- AIRCRAFT" | state == "ATLANTA -- ART-CMBT VEHICLES"
	replace state = "GEORGIA" if state == "ATLANTA -- AIRCRAFT" | state == "ATLANTA -- ART-CMBT VEHICLES"
replace city = "BOSTON" if state == "BOSTON -- AIRCRAFT" | state == "BOSTON -- SHIPBUILDING"
	replace state = "MASSACHUSETTS" if state == "BOSTON -- AIRCRAFT" | state == "BOSTON -- SHIPBUILDING"
replace state = "CALIFORNIA" if state == "CALIF"
replace state = "MAINE" if state == "CENTRAL AND NORTHERN MAINE"
replace state = "MASSACHUSETTS" if state == "CENTRAL AND WESTERN MASSACHUSETTS"
replace state = "NORTH CAROLINA" if state == "CENTRAL NORTH CAROLINA" | state == "SOUTHEASTERN NORTH CAROLINA"
replace city = "CHICAGO" if state == "CHICAGO -- AIRCRAFT" | state == "CHICAGO -- AMMUNITION" | state == "CHICAGO -- ELECTRONICS"
	replace state = "ILLINOIS" if state == "CHICAGO -- AIRCRAFT" | state == "CHICAGO -- AMMUNITION" | state == "CHICAGO -- ELECTRONICS"
replace city = "CLEVELAND" if state == "CLEVELAND" | state == "CLEVELAND -- AIRCRAFT"
	replace state = "OHIO" if state == "CLEVELAND" | state == "CLEVELAND -- AIRCRAFT"
replace city = "DALLAS-FORT WORTH" if state == "DALLAS-FORT WORTH -- AIRCRAFT" | state == "DALLAS-FORT WORTH--ART-CMBT VEH"
	replace state = "TEXAS" if state == "DALLAS-FORT WORTH -- AIRCRAFT" | state == "DALLAS-FORT WORTH--ART-CMBT VEH"
replace state = "SOUTH DAKOTA" if state == "EASTERN SOUTH DAKOTA"
replace state = "TENNESSEE" if state == "EASTERN TENNESSEE"
replace city = "FORT WAYNE-MARION" if state == "FT WAYNE-MARION -- ELECTRONICS"
	replace state = "INDIANA" if state == "FT WAYNE-MARION -- ELECTRONICS"
replace state = "MARYLAND" if state == "MD"
replace city = "MEMPHIS" if state == "MEMPHIS -- ART-CMBT-VEH"
	replace state = "TENNESSEE" if state == "MEMPHIS -- ART-CMBT-VEH"
replace city = "NASHVILLE" if state == "NASHVILLE -- ART-CMBT VEHICLES"
	replace state = "TENNESSEE" if state == "NASHVILLE -- ART-CMBT VEHICLES"
replace city = "NEW LONDON" if state == "NEW LONDON -- SHIPBUILDING"
	replace state = "CONNECTICUT" if state == "NEW LONDON -- SHIPBUILDING"
replace state = "NEW YORK" if state == "NEW YORK- BRONX" | state == "NEW YORK- BROOKLYN" ///
	| state == "NEW YORK- BRX & BKLYN VA HOSP" | state == "NEW YORK- FT. MONMOUTH" ///
	| state == "NEW YORK- MANHATTAN" | state == "NEW YORK- NORTHPORT VA HOSP" ///
	| state == "NEW YORK- PICATINNY ARSENAL"
replace city = "NORFOLK" if state == "NORFOLK-PORTSMOTH-NEWPORT NEWS-HAMPTON"
	replace state = "VIRGINIA" if state == "NORFOLK-PORTSMOTH-NEWPORT NEWS-HAMPTON"
replace state = "ARIZONA" if state == "NORTHEASTERN ARIZONA"
replace state = "NEW YORK" if state == "NORTHERN NEW YORK"
replace state = "MICHIGAN" if state == "NORTHWESTERN MICHIGAN"
replace city = "PHILADELPHIA" if state == "PHILADELPHIA -- AIRCRAFT" | state == "PHILADELPHIA -- AIRCRAFT FULL SCALE 89" ///
	| state == "PHILADELPHIA -- ELECTRONICS" | state == "PHILADELPHIA -- GUIDED MISSILES" ///
	| state == "PHILADELPHIA CLOTHING SURVEY--HOURLY" | state == "PHILADELPHIA CLOTHING SURVEY--PIECEWORK"
	replace state = "PENNSYLVANIA" if state == "PHILADELPHIA -- AIRCRAFT" | state == "PHILADELPHIA -- AIRCRAFT FULL SCALE 89" ///
		| state == "PHILADELPHIA -- ELECTRONICS" | state == "PHILADELPHIA -- GUIDED MISSILES" ///
		| state == "PHILADELPHIA CLOTHING SURVEY--HOURLY" | state == "PHILADELPHIA CLOTHING SURVEY--PIECEWORK"
replace city = "PHOENIX" if state == "PHOENIX -- AIRCRAFT"
	replace state = "ARIZONA" if state == "PHOENIX -- AIRCRAFT"
replace city = "PITTSBURGH" if state == "PITTSBURGH -- ELECTRONICS"
	replace state = "PENNSYLVANIA" if state == "PITTSBURGH -- ELECTRONICS"
replace city = "SAN DIEGO" if state == "SAN DIEGO -- AIRCRAFT" | state == "SAN DIEGO -- SHIPBUILDING"
	replace state = "CALIFORNIA" if state == "SAN DIEGO -- AIRCRAFT" | state == "SAN DIEGO -- SHIPBUILDING"
replace city = "SAN FRANCISCO" if state == "SAN FRANCISCO -- AIRCRAFT" | state == "SAN FRANCISCO -- ELECTRONICS"
	replace state = "CALIFORNIA" if state == "SAN FRANCISCO -- AIRCRAFT" | state == "SAN FRANCISCO -- ELECTRONICS"
replace state = "COLORADO" if state == "SOUTHERN & WESTERN COLORADO"
replace state = "MISSOURI" if state == "SOUTHERN MISSOURI"
replace state = "MICHIGAN" if state == "SOUTHWESTERN MICHIGAN"
replace state = "OREGON" if state == "SOUTHWESTERN OREGON"
replace state = "WISCONSIN" if state == "SOUTHWESTERN WISCONSIN"
replace city = "SYRACUSE" if state == "SYRACUSE -- ART-CMBT VEHICLES"
	replace state = "NEW YORK" if state == "SYRACUSE -- ART-CMBT VEHICLES"
replace city = "TULSA" if state == "TULSA -- AIRCRAFT"
	replace state = "OKLAHOMA" if state == "TULSA -- AIRCRAFT"
replace city = "TEXARKANA" if state == "TEXARKANA -- AMMUNITION"
	replace state = "TEXAS" if state == "TEXARKANA -- AMMUNITION"
replace state = "TEXAS" if state == "WESTERN TEXAS" | state=="TX" | state=="TX-SOUTHWESTERN OKLAHOMA"
replace city = "WICHITA" if state == "WICHITA -- AIRCRAFT"
	replace state = "KANSAS" if state == "WICHITA -- AIRCRAFT"
replace state = "VIRGINIA" if state == "NORFOLK-PORTSMOUTH-NEWPORT NEWS-HAMPTON"
replace state = "UTAH" if state == "UTAH -- AIRCRAFT"
replace city = "MIAMI" if state == "MIAMI -- AIRCRAFT"
	replace state = "FLORIDA" if state == "MIAMI -- AIRCRAFT"
replace city = "DOTHAN" if state == "DOTHAN -- AIRCRAFT"
	replace state = "ALABAMA" if state == "DOTHAN -- AIRCRAFT"
	replace state= "WASHINGTON" if state=="SOUTHEASTERN WASHINGTON-EASTERN OREGON"
